# Generated by Django 3.2.6 on 2021-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=200)),
                ('Image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
