# Generated by Django 3.2.6 on 2021-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Icons', models.TextField(max_length=200)),
                ('Content', models.TextField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='Content',
            field=models.TextField(max_length=600),
        ),
    ]
