# Generated by Django 3.2.6 on 2021-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210912_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team')),
                ('Name', models.CharField(max_length=100)),
                ('Title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
    ]
