# Generated by Django 3.2.6 on 2021-09-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
        ('blog', '0006_remove_post_slug'),
    ]

    operations = [
    ]
